name = "Liquidsoap"
grammar = "liquidsoap"
path_suffixes = ["liq"]
line_comments = ["# "]
tab_size = 2
autoclose_before = "}])"
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "\"", end = "\"", close = true, newline = false, not_in = ["comment", "string"] },
    { start = "#<", end = ">#", close = true, newline = true, not_in = ["string"] },
    { start = "#{", end = "}", close = true, newline = false },
    { start = "def", end = "end", close = false, newline = true, not_in = ["comment", "string"] },
    { start = "then", end = "end", close = false, newline = true, not_in = ["comment", "string"] },
    { start = "then", end = "elsif", close = false, newline = true, not_in = ["comment", "string"] },
    { start = "then", end = "else", close = false, newline = true, not_in = ["comment", "string"] },
]
increase_indent_pattern = '(^\s*(def|if|elsif|else|then)\b$|^.*\s*=$)'
decrease_indent_pattern = '(^\s*(end|elsif|else|then)\b$)'
